
function st_struct=init_st_struct_rms(nb_targets)

st_struct=struct(...
    'TS_comp',nan(1,nb_targets),...
    'TS_uncomp',nan(1,nb_targets),...
    'Power_norm',nan(1,nb_targets),...
    'Target_range',nan(1,nb_targets),...
    'Target_range_min',nan(1,nb_targets),...
    'Target_range_max',nan(1,nb_targets),...
    'idx_r',nan(1,nb_targets),...
    'Angle_minor_axis',nan(1,nb_targets),...
    'Angle_major_axis',nan(1,nb_targets),...
    'Ping_number',nan(1,nb_targets),...
    'Time',nan(1,nb_targets),...
    'idx_target_lin',nan(1,nb_targets),...
    'pulse_env_before_lin',nan(1,nb_targets),...
    'pulse_env_after_lin',nan(1,nb_targets),...
    'TargetLength',nan(1,nb_targets),...
    'PulseLength_Normalized_PLDL',nan(1,nb_targets),...
    'Transmitted_pulse_length',nan(1,nb_targets));
end