function [xplot1,yplot1,rsq_adj,figure1,axes1] = regress_fit(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of scatter x data
%  Y1:  vector of scatter y data

%  Auto-generated by MATLAB on 18-Mar-2024 19:31:37

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter1 = scatter(X1,Y1,15,'filled','o','MarkerFaceColor',"black",MarkerFaceAlpha=0.5);
xlim([min(X1) max(X1)]);
grid on;
% Get xdata from plot
xdata1 = get(scatter1, 'xdata');
% Get ydata from plot
ydata1 = get(scatter1, 'ydata');
% Make sure data are column vectors
xdata1 = xdata1(:);
ydata1 = ydata1(:);


% Remove NaN values and warn
nanMask1 = isnan(xdata1(:)) | isnan(ydata1(:));
if any(nanMask1)
    warning('GeneratedCode:IgnoringNaNs', ...
        'Data points with NaN coordinates will be ignored.');
    xdata1(nanMask1) = [];
    ydata1(nanMask1) = [];
end

% Find x values for plotting the fit based on xlim
axesLimits1 = xlim(axes1);
%xplot1 = linspace(axesLimits1(1), axesLimits1(2));
xplot1 = 1:length(xdata1);

% Preallocate for "Show equations" coefficients
coeffs1 = cell(1,1);

% Find coefficients for polynomial (order = 10)
[fitResults1,S,mu1] = polyfit(xdata1,ydata1,10);
% Evaluate polynomial
[yplot1,delta] = polyval(fitResults1,xplot1,S,mu1); %shortened Xlength
[yplot2,delta2] = polyval(fitResults1,xdata1,S,mu1); %True xlength

% Calcualte RSquare
yresid = ydata1 - yplot2;
SSresid = sum(yresid.^2);
SStotal = (length(ydata1)-1) * var(ydata1);
rsq = 1 - SSresid/SStotal;
rsq_adj = 1 - SSresid/SStotal * (length(ydata1)-1)/(length(ydata1)-length(fitResults1));
% Save type of fit for "Show equations"
fittypesArray1(1) = 11;

% Save coefficients for "Show Equation"
coeffs1{1} = fitResults1;

%conf bounds
distfromtrend = sqrt(xplot1.^2 + yplot1.^2);
scatter1.AlphaData = distfromtrend;

xconf = [xplot1 xplot1(end:-1:1)];
yconf = [yplot1+2*delta yplot1(end:-1:1)-2*delta];
% Plot the fit
fitLine1 = plot(xplot1,yplot1,'DisplayName','   10th degree',...
    'XLimInclude','off',...
    'Tag','10th degree',...
    'Parent',axes1,...
    'MarkerSize',6,...
    'Color','#FF0000',...
    'LineWidth',2);
hold on
p = fill(xconf,yconf,'red');
p.FaceColor = [1 0.8 0.8];      
p.EdgeColor = 'none'; 
%ci = plot(xplot1,yplot1+2*delta,'r--',xplot1,yplot1-2*delta,'r--')
%ci(1).LineWidth = 2;
%ci(2).LineWidth = 2;
% Set new line in proper position
setLineOrder(axes1,fitLine1,scatter1);
ord = get(gca, 'Children');
temp = ord(2);
ord(2) = ord(3);
ord(3) = temp;
%set(gca, 'Children', flipud(get(gca, 'Children')) )
set(gca, 'Children', ord)
set(gca, 'Children', flipud(get(gca, 'Children')) )
% "Show equations" was selected
showEquations(fittypesArray1,coeffs1,4,axes1,xdata1,rsq_adj);

% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[min(ydata1) max(ydata1)]);
hold(axes1,'off');
% Create legend
legend(axes1,'show');

%-------------------------------------------------------------------------%
function setLineOrder(axesh1, newLine1, associatedLine1)
%SETLINEORDER(AXESH1,NEWLINE1,ASSOCIATEDLINE1)
%  Set line order
%  AXESH1:  axes
%  NEWLINE1:  new line
%  ASSOCIATEDLINE1:  associated line

% Get the axes children
hChildren = get(axesh1,'Children');
% Remove the new line
hChildren(hChildren==newLine1) = [];
% Get the index to the associatedLine
lineIndex = find(hChildren==associatedLine1);
% Reorder lines so the new line appears with associated data
hNewChildren = [hChildren(1:lineIndex-1);newLine1;hChildren(lineIndex:end)];
% Set the children:
set(axesh1,'Children',hNewChildren);

%-------------------------------------------------------------------------%
function showEquations(fittypes1, coeffs1, digits1, axesh1, xdata1, rsq_adj)
%SHOWEQUATIONS(FITTYPES1,COEFFS1,DIGITS1,AXESH1,XDATA1)
%  Show equations
%  FITTYPES1:  types of fits
%  COEFFS1:  coefficients
%  DIGITS1:  number of significant digits
%  AXESH1:  axes
%  XDATA1:  x data

% n = length(fittypes1);
% txt = cell(length(n + 2) ,1);
% txt{1,:} = ' ';
% for i = 1:n
%     txt{i + 1,:} = getEquationString(fittypes1(i),coeffs1{i},digits1,axesh1);
% end
% meanx = mean(xdata1);
% stdx = std(xdata1);
% format = ['where z = (x - %0.', num2str(digits1), 'g)/%0.', num2str(digits1), 'g'];
txt = sprintf('R^2 = %0.3f',rsq_adj);

text(.05,.95,txt,'parent',axesh1, ...
    'verticalalignment','top','units','normalized');

%-------------------------------------------------------------------------%
function [s1, a1] = getEquationString(fittype1, coeffs1, digits1, axesh1)
%GETEQUATIONSTRING(FITTYPE1,COEFFS1,DIGITS1,AXESH1)
%  Get "Show Equation" text
%  FITTYPE1:  type of fit
%  COEFFS1:  coefficients
%  DIGITS1:  number of significant digits
%  AXESH1:  axes

if isequal(fittype1, 0)
    s1 = 'Cubic spline interpolant';
elseif isequal(fittype1, 1)
    s1 = 'Shape-preserving interpolant';
else
    if isequal(fittype1, 2)
        a1 = 'Linear: ';
    elseif isequal(fittype1, 3)
        a1 = 'Quadratic: ';
    elseif isequal(fittype1, 4)
        a1 = 'Cubic: ';
    elseif isequal(fittype1, 5)
        a1 = '4th degree: ';
    elseif isequal(fittype1, 6)
        a1 = '5th degree: ';
    elseif isequal(fittype1, 7)
        a1 = '6th degree: ';
    elseif isequal(fittype1, 8)
        a1 = '7th degree: ';
    elseif isequal(fittype1, 9)
        a1 = '8th degree: ';
    elseif isequal(fittype1, 10)
        a1 = '9th degree: ';
    elseif isequal(fittype1, 11)
        a1 = '10th degree: ';
    end
    op = '+-';
    format1 = ['%s %0.',num2str(digits1),'g*z^{%s} %s'];
    format2 = ['%s %0.',num2str(digits1),'g'];
    xl = get(axesh1, 'xlim');
    fit =  fittype1 - 1;
    s1 = sprintf('%s y =',a1);
    th = text(xl*[.95;.05],1,s1,'parent',axesh1, 'vis','off');
    if abs(coeffs1(1) < 0)
        s1 = [s1 ' -'];
    end
    for i = 1:fit
        sl = length(s1);
        if ~isequal(coeffs1(i),0) % if exactly zero, skip it
            s1 = sprintf(format1,s1,abs(coeffs1(i)),num2str(fit+1-i), op((coeffs1(i+1)<0)+1));
        end
        if (i==fit) && ~isequal(coeffs1(i),0)
            s1(end-5:end-2) = []; % change x^1 to x.
        end
        set(th,'string',s1);
        et = get(th,'extent');
        if et(1)+et(3) > xl(2)
            s1 = [s1(1:sl) sprintf('\n     ') s1(sl+1:end)];
        end
    end
    if ~isequal(coeffs1(fit+1),0)
        sl = length(s1);
        s1 = sprintf(format2,s1,abs(coeffs1(fit+1)));
        set(th,'string',s1);
        et = get(th,'extent');
        if et(1)+et(3) > xl(2)
            s1 = [s1(1:sl) sprintf('\n     ') s1(sl+1:end)];
        end
    end
    delete(th);
    % Delete last "+"
    if isequal(s1(end),'+')
        s1(end-1:end) = []; % There is always a space before the +.
    end
    if length(s1) == 3
        s1 = sprintf(format2,s1,0);
    end
end

